### ISSUE TITLE
Under Xiaomi HyperOS, there is a notification bar error.

### ISSUE THREAD

**Issue by btbirdy** [XilinJia/Podcini#128]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.15.4

### Where did you get the app from

Other

### Android version

hyperos

### Device model

xiaomi14

### Steps to reproduce

During playback, when swiping down the notification bar or locking the screen, it will automatically skip to the next track until the last one. This issue used to occur with AntennaPod as well. It doesn't happen every time, but it appears in about 80% of the cases.
播放时，下滑通知栏，或者锁屏，会自动跳到下一个直到最后一个。以前antennapod也有这样的问题。不是每次都出现，80%情况下会出现。

### Expected behaviour

Playing normally

### Current behaviour

it will automatically skip to the next track until the last one

**Comment by XilinJia** [comment]
When it happens again, can you do:
Settings -> Report bug, click the upper right bar and select "Export detailed logs",
then attach that log here?

**Comment by btbirdy** [comment]
[full-logs.txt](https://github.com/user-attachments/files/18055484/full-logs.txt)
logs
另外，倍速播放不生效

**Comment by XilinJia** [comment]
Thanks for the log.  There are some strange things there, but I don't see repeated pattern like playing one after another.

So it's between 10:15 and 10:16.  I see only 3 episodes recorded:
187.支付宝20年对话陈亮
香港电台DJ黄志淙专访
E168 大可不必先苦后甜

There were a couple strange exceptions but I can't say they are related to the issue:

1. UnknownHostException: Unable to resolve host "keychange.xyz": No address associated with hostname, related to:
PodciniHttpClient$BasicAuthorizationInterceptor.intercept(PodciniHttpClient.kt:226

2. java.net.MalformedURLException: invalid port: content, related to HttpDownloader.download(HttpDownloader.kt:38

You were trying to download something?

Can you describe a bit more in detail on what you were doing then, what happened, and perhaps how many episodes in the queue, etc?

> 倍速播放不生效

That's a bummer.  the HypeOS doesn't fully implement media3?

**Comment by btbirdy** [comment]
1. Automatically skipping to the next track
Operation process:
When Podcini is playing, if you slide down to view the notification bar, Podcini automatically skips to the next track, then quickly to the next one, until it reaches the last one. Or if you exit the notification bar, it plays the track it skipped to. As seen in the logs, when playing "187.支付宝20年对话陈亮" sliding to the notification bar caused it to automatically skip to "香港电台DJ黄志淙专访" and then to "168 大可不必先苦后甜" Sliding away the notification bar returns to normal playback.
AntennaPod has the same issue, while Podcast Addict does not have this problem.
2. Playback speed control
Using AntennaPod allows for normal playback speed adjustment.

**Comment by XilinJia** [comment]
Can you set a speed and play something then attach a log here?  I'd like to see what complaint it has.

**Comment by XilinJia** [comment]
> deselect "Skip Track" and "Next Chapter"

I see. that's interesting.

**Comment by XilinJia** [comment]
Though I'm not positive, this might be related to the speed issue:

```
12-10 20:55:20.516 11487 18967 W DefaultAudioSink: Failed to set playback params
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:   java.lang.IllegalArgumentException: arguments out of range
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at android.media.AudioTrack.native_set_playback_params(Native Method)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at android.media.AudioTrack.setPlaybackParams(AudioTrack.java:2837)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at androidx.media3.exoplayer.audio.DefaultAudioSink.setAudioTrackPlaybackParametersV23(DefaultAudioSink.java:1634)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at androidx.media3.exoplayer.audio.DefaultAudioSink.setPlaybackParameters(DefaultAudioSink.java:1371)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.setPlaybackParameters(MediaCodecAudioRenderer.java:762)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at androidx.media3.exoplayer.DefaultMediaClock.setPlaybackParameters(DefaultMediaClock.java:151)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at androidx.media3.exoplayer.ExoPlayerImplInternal.setMediaClockPlaybackParameters(ExoPlayerImplInternal.java:1084)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at androidx.media3.exoplayer.ExoPlayerImplInternal.setPlaybackParametersInternal(ExoPlayerImplInternal.java:1507)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:568)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at android.os.Handler.dispatchMessage(Handler.java:103)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at android.os.Looper.loopOnce(Looper.java:249)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at android.os.Looper.loop(Looper.java:337)
12-10 20:55:20.516 11487 18967 W DefaultAudioSink:       at android.os.HandlerThread.run(HandlerThread.java:85)
```

Will check about what exactly that means.

The log also has some strange things like:

```
12-10 20:55:17.602 11487 18967 W AudioCapabilities: Unsupported mime audio/alac
12-10 20:55:17.603 11487 18967 W AudioCapabilities: Unsupported mime audio/x-ape
12-10 20:55:17.603 11487 18967 W AudioCapabilities: Unsupported mime audio/dsd
12-10 20:55:17.603 11487 18967 W AudioCapabilities: Unsupported mime audio/amr-wb-plus
12-10 20:55:17.603 11487 18967 W AudioCapabilities: Unsupported mime audio/amr-wb+
12-10 20:55:17.603 11487 18967 W AudioCapabilities: Unsupported mime audio/x-ms-wma
12-10 20:55:17.603 11487 18967 W AudioCapabilities: Unsupported mime audio/alac
12-10 20:55:17.603 11487 18967 W AudioCapabilities: Unsupported mime audio/x-ape

12-10 20:55:17.607 11487 18967 W VideoCapabilities: Unsupported mime image/vnd.android.heic
12-10 20:55:17.607 11487 18967 W VideoCapabilities: Unsupported mime image/vnd.android.heic
12-10 20:55:17.607 11487 18967 W VideoCapabilities: Unsupported mime video/dolby-vision
12-10 20:55:17.607 11487 18967 W VideoCapabilities: Unsupported mime video/dolby-vision
12-10 20:55:17.607 11487 18967 W VideoCapabilities: Unsupported mime video/dolby-vision

12-10 20:55:17.713 11487 18966 W AudioSystem-JNI: Unknown native audio format for JAVA API: 452984832
12-10 20:55:17.713 11487 18966 W AudioSystem-JNI: Unknown native audio format for JAVA API: 469762048
12-10 20:55:17.713 11487 18966 W AudioSystem-JNI: Unknown native audio format for JAVA API: 486539264
12-10 20:55:17.713 11487 18966 W AudioSystem-JNI: Unknown native audio format for JAVA API: 352321536
12-10 20:55:17.713 11487 18966 W AudioSystem-JNI: Unknown native audio format for JAVA API: 369098752
12-10 20:55:17.713 11487 18966 W AudioSystem-JNI: Unknown native audio format for JAVA API: 117440512
```

**Comment by XilinJia** [comment]
Regarding the skipping, it appears, for some reason, the system calls media3's  session callback function with skip command:

```
12-09 10:15:40.610 26548 26548 D PlaybackService: MyMediaSessionCallback onCustomCommand 3_SKIP
12-09 10:15:40.829 26548 26548 D PlaybackService: MyMediaSessionCallback onCustomCommand 3_SKIP
12-09 10:15:40.990 26548 10785 I .mdiq.podcini.R: This is non sticky GC, maxfree is 16777216 minfree is 8388608
12-09 10:15:41.259 26548 26548 D PlaybackService: MyMediaSessionCallback onCustomCommand 3_SKIP
12-09 10:15:41.928 26548 26548 D PlaybackService: MyMediaSessionCallback onCustomCommand 3_SKIP
```

**Comment by XilinJia** [comment]
> which is to deselect "Skip Track" and "Next Chapter" in the playback notification settings

Can you explain how and where you did this?

**Comment by btbirdy** [comment]
> > which is to deselect "Skip Track" and "Next Chapter" in the playback notification settings
> 
> Can you explain how and where you did this?
The operations I perform in AntennaPod are in Chinese, and may not be entirely accurate.
setting → user interface → “设置播放通知”

**Comment by XilinJia** [comment]
> The operations I perform in AntennaPod are in Chinese, and may not be entirely accurate.
> setting → user interface → “设置播放通知”

So in AntennaPod you deselected "Skip Track" and "Next Chapter" and you avoided the problem. That makes sense as I mentioned the system keeps sending Skip commands. If the Skip commands are ignored, then you are not affected.

The settings are not used in Podcini after migrating to media3.  Perhaps I will see to enable them.

**Comment by XilinJia** [comment]
Added the Skip option in 6.15.9 (at the same settings spot).  Let me know how that works.

**Comment by XilinJia** [comment]
seems nothing more to do.
