### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by firefoxlover** [XilinJia/Podcini#23]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.3.2

### Where did you get the app from

Other

### Android version

14 GrapheneOS

### Device model

pixel 6a

### First occurred

today

### Steps to reproduce

Opened the app, wanted to stream a podcast and reproducible crash

Using cell data, not wifi

```
type: crash
osVersion: google/bluejay/bluejay:14/AP1A.240305.019.A1/2024032100:user/release-keys
package: ac.mdiq.podcini:3020113
process: ac.mdiq.podcini
processUptime: 2103 + 880 ms
installer: dev.imranr.obtainium

java.lang.ClassCastException: com.skydoves.balloon.radius.RadiusLayout cannot be cast to android.widget.LinearLayout
	at ac.mdiq.podcini.databinding.PopupBubbleViewBinding.bind(SourceFile:90)
	at ac.mdiq.podcini.ui.fragment.EpisodeInfoFragment.showOnDemandConfigBalloon(SourceFile:201)
	at ac.mdiq.podcini.ui.fragment.EpisodeInfoFragment.onCreateView$lambda$4(SourceFile:156)
	at ac.mdiq.podcini.ui.fragment.EpisodeInfoFragment.$r8$lambda$sT8PAb8QM9o-mjaDyq58X397K5Y(SourceFile:0)
	at ac.mdiq.podcini.ui.fragment.EpisodeInfoFragment$$ExternalSyntheticLambda9.onClick(SourceFile:0)
	at android.view.View.performClick(View.java:7729)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30484)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

### Expected behaviour

Not crashing

### Current behaviour

Crashes

**Comment by XilinJia** [comment]
got it.  a viewbinding error, not necessarily has to do with mobile or wifi.  fixed in the coming 4.4.1
