### ISSUE TITLE
Crash when mark episode as played 6.3.2

### ISSUE THREAD

**Issue by metronidazole** [XilinJia/Podcini#77]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.3.2

### Where did you get the app from

Other

### Android version

14

### Steps to reproduce

1. Go to queue
2. Open episode view
3. Press mark as played button

### Expected behaviour

Episode should be marked as played

### Current behaviour

Crash

## Crash info
Podcini version: 6.3.2

## StackTrace
```
java.lang.IllegalStateException: [RLM_ERR_WRONG_TRANSACTION_STATE]: Trying to modify database while in read transaction
	at io.realm.kotlin.internal.interop.CoreErrorConverter.asThrowable(SourceFile:47)
	at io.realm.kotlin.internal.interop.realmcJNI.realm_set_value(Native Method)
	at io.realm.kotlin.internal.interop.realmc.realm_set_value(SourceFile:676)
	at io.realm.kotlin.internal.interop.RealmInterop.realm_set_value-wOxPcJY(SourceFile:498)
	at io.realm.kotlin.internal.RealmObjectHelper.setValueTransportByKey-WQPMd18$io_realm_kotlin_library(SourceFile:675)
	at ac.mdiq.podcini.storage.model.Episode.setPlayState(SourceFile:204)
	at ac.mdiq.podcini.storage.model.Episode.setPlayed(SourceFile:198)
	at ac.mdiq.podcini.ui.actions.menuhandler.EpisodeMenuHandler.onMenuItemClicked(SourceFile:143)
	at ac.mdiq.podcini.ui.fragment.EpisodeInfoFragment.onMenuItemClick(SourceFile:220)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(SourceFile:224)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(SourceFile:769)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(SourceFile:833)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(SourceFile:157)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(SourceFile:984)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(SourceFile:974)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(SourceFile:620)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(SourceFile:155)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by XilinJia** [comment]
fixed in 6.3.3
