### ISSUE TITLE
Volume adaption [bug]

### ISSUE THREAD

**Issue by Jackie7610** [XilinJia/Podcini#91]
To put it simply -

The volume adaption does not work. 

I tried this on various podcasts changing from "no adaption" to "heavy boost". The result? It sounds the same without any increase in volume. Same goes to volume reduction. Could you please look into it?

Podcini version: 6.6.5
Download source : Github
Device : Galaxy A32

One more thing...the volume adaption is working on Antennapod so I guess nothing is wrong with my device?

**Comment by XilinJia** [comment]
Volume adaptation works on my Samsung Android 14 phone.
The numbers were 0.2, 0.5, 1, 1.5, 2, 2.5. Changing among them was noticeable to me.  The boosts were not great (I guess the numbers were inherited from AP).  in version 6.6.6, I changed these to:
 0.2, 0.5, 1, 2, 4, 7 (the max boost being 6dB).

Note, when you change the scale, you need to re-play the episode.

**Comment by Jackie7610** [comment]
Greetings dev. The volume adaption works now after selecting the required boost level after pausing the episode. Hitting play applies the boost but now I'm getting a lot of distortions on medium and heavy boost level. I dont know if this should be happening. This is happening with version 6.6.6 but not with version 6.6.5

**Comment by XilinJia** [comment]
Good.
The distortion could mean the new boost numbers are too high for the speaker of the phone (at medium level it's 3dB higher). I will play with the numbers a bit and get a better compromise.

**Comment by XilinJia** [comment]
tuned the numbers somewhat in 6.6.7

**Comment by Jackie7610** [comment]
Yes now the volume adaption works. Just need to pause and play after selecting the boost level. Easy. 

I do have some questions though...it's about the progress bar. It shows time as if it's leaping a few seconds. It goes like 00:00 (after 10 seconds) it's 00:10 (I don't get to see the rest of the seconds like 00:05, 00:06 etc). 

And the progress bar is really on the edges and it get's difficult for fat fingers like mine :)

And the "now playing" is half-ugly. I don't know the right word. The album art is down and the description is on top (no issues) but when the description of a podcast is long swiping down to view the album art shows 2-4 lines of the description on top like it is not fitting in one page. 

Should I be creating a new issue about it?

Sorry for ranting though. Love the modification of antennapod.

**Comment by XilinJia** [comment]
The progress bar is set to update every 5 seconds, in the same frequency as persisting progress into the DB, to conserve some energy.  Do you feel a strong need to see it every second?

The "now playing" (or player detailed view), yes, I made the description to the beginning as I think that's more important for understanding about the current episode, especially when the description is sort of like a transcript.  So you feel like to see the art work in the beginning?  Explain why.

I agree the progress bar on the bottom player UI is pretty much on the edge, though I don't have much trouble dragging it (my finger is not too thin).  How would you suggest to improve it?

No, you don't need to open a new issue.  Just explain here. I'd love to hear great ideas.

**Comment by Jackie7610** [comment]
The first one. Not it's not so important. I just thought it's a bug or something. But yes...I really don't stare at the duration. 

The second one...it really doesn't matter if the artwork comes first or second. It's just that the last part of the description and the artwork they're in the same page and sometimes it looks odd. 

for example the top of my screen displays the underline of a link given in a description and above the underline I see half alphabets and numbers. I would try to grab a screenshot as this happens on specific podcast episodes due to the difference in it's description. 


The third one can be adjusted via padding? I mean if it's possible.

**Comment by XilinJia** [comment]
> Switching from list view to grid option if implemented to the subscription page would be an easy switch?

This is in 6.8.5

> Switching from list view to grid option if implemented to the subscription page would be an easy switch?

What's your intention?  Do you feel the current brightness is too much for the eyes?

**Comment by Jackie7610** [comment]
> What's your intention? Do you feel the current brightness is too much for the eyes?

Is it about the play/pause, rewind, etc buttons? Yes they were very light in contrast with the background sometimes making it hard to view. But after a few "pre-releases" it's fixed. I guess it's because of the Jetpack compose? 

But man...the progress bar has stretched to the edges.

**Comment by XilinJia** [comment]
Are you on light theme? I meant to make the buttons less visible (darker) in dark theme so that they don't produce too much shine to the eyes. For light theme, I'm not too sure what they were like.  I will try to tune them shortly.  The idea is that they don't need to be too obvious to the extent that they shine too much (in dark theme). For light theme, they should definitely be very dark.  

> the progress bar has stretched to the edges

explain what you mean. The progress bar is even wider now with Compose, and it's not really at the edge, as the episode title is above it, so dragging the bar is not quite likely interfering with others.

**Comment by Jackie7610** [comment]
The progress bar looks like this on my screen

 https://imgur.com/a/ypjU4eC

I don't know how it looks or behaves on other devices. But say if I want to drag it a few seconds forward for a podcast that is more than an hour long, the back gesture gets triggered or sometimes the side panel opens up.


I found more bugs. Give me time. I'll get back to you

**Comment by XilinJia** [comment]
Yes, the progress bar looks the same with me. 
If you have hour-long episode and you want to move forward a few seconds, dragging progress bar is not practical, you'd better use the fast-forward button. You can configure the number of second per tap for the button in Settings -> Playback. The progress bar is better for larger move in position.  And BTW, you can also tap on a position in the bar without dragging.

**Comment by XilinJia** [comment]
@Jackie7610, excellent report of bugs.

**Comment by XilinJia** [comment]
regarding MILLIPEDE, I suspect you set "use episode cover" in Settings -> Interface. It takes time to download them the first time you open the list.  Can you unset it and let me what happens. I scroll through list (the AllEpisodes view) with 32,000 episodes, and it seems to work fine.

Some of the color issues will need some overall adjustments as some strange colors like purple can be simply due to switch from View to Material to Material3.

can't reproduce LOCUST.
can't reproduce MOSQUITO.
Can you provide more details on the situations you were in?

I'v marked some others as fixed.

**Comment by XilinJia** [comment]
in 6.8.6, long-press on a online feed prompts you to subscribe directly.

**Comment by Jackie7610** [comment]
> regarding MILLIPEDE, I suspect you set "use episode cover" in Settings -> Interface. It takes time to download them the first time you open the list. Can you unset it and let me what happens.

I did had. I have unchecked the option. But yet it occurs. :(

> Some of the color issues will need some overall adjustments as some strange colors like purple can be simply due to switch from View to Material to Material3

No issues. I can wait till it's back to normal. 

> can't reproduce LOCUST.

Appologies as I forgot to mention. My bad. This happens with youtube videos. 

- Search a youtube channel in podcini and subscribe it. 
- Head over to settings and toggle "audio only" mode for youtube videos.
- Now play any file from the subscribed youtube channel.
- Tap the album art below and
- You'll see the locust destroying crops. 

> can't reproduce MOSQUITO.

I just play any podcast, be it from a youtube channel or normal podcast. I tap anywhere on the notification progress bar and that happens. That MOSQUITO... It just entered the room while the windows and doors were closed. I don't know how it got it. The bug was there since 6.7.3 even before the pre-releases. 

The COCKROACH is half alive. It still drags itself with 1 leg. The "deselect all" still doesn't work. 

The CRICKET while is not chirping anymore...it's still sits there silent. Clearing the history while does not crash the app it does not clear it also. 


I really appreciate the effort you put in Podcini dev. Thank you ❤️

**Comment by XilinJia** [comment]
resolved clear history and deselect all in 6.8.7.

**Comment by XilinJia** [comment]
LOCUST appears no problem for me (6.8.6) with Youtube channels. Which channel causes it for you?

**Comment by Jackie7610** [comment]
> Which channel causes it for you?

Any youtube channel. Any of them...it doesn't matter if it has 10M subscriber or 27 subscribers. This happens mostly with youtube channel IF and WHILE using "Audio only" mode. Video mode plays well.

**Comment by XilinJia** [comment]
found some anomaly on LOCUST, though not crashing on me.  the fix in 6.8.7 likely fixes your problem.

**Comment by XilinJia** [comment]
Hum. Your device is Galaxy A32. What's it's memory and Android version?

**Comment by Jackie7610** [comment]
> Your device is Galaxy A32. What's it's memory and Android version?

It has 6GB of RAM but I've increased it to 8GB with RAM Plus and has 128GB of internal storage. It's running on Android 13. One UI 5.1

**Comment by XilinJia** [comment]
See if 6.9.0 improves your situation.

**Comment by Jackie7610** [comment]
It didn't. It still lags when I scroll. Let me see if I can grab a log when it crashes

**Comment by XilinJia** [comment]
Regarding WEEVIL, the limit of episodes for a youtube channel or playlist has been changed in various versions, currently with 6.9.0 is 1000. When it's changed, it only affects new subscriptions. And the limit is only for the initial subscribing. When you later update the subscription, the newer episodes should come in though the older ones don't, and the total number of episodes can grow and there is no limit there.

**Comment by XilinJia** [comment]
> create categories of podcasts in subscriptions

You can do this in the setting of every subscription, or through multi-selection menu in Subscriptions.

> A quick 1-minute preview of the podcast before subscribing

In OnlineFeed view where you subscribe, you can tap Episodes button and play (stream) any episode in the list as normal.

Does LOCUST still happen to you? how about on a newly subscribed channel?

**Comment by Jackie7610** [comment]
> You can do this in the setting of every subscription, or through multi-selection menu in Subscriptions. Then you can filter based on your tags in the spinner at the upper-right of the Subscriptions view.

Aye aye capt' 😃

> In OnlineFeed view where you subscribe, you can tap Episodes button and play (stream) any episode in the list as normal.

Yes, but that's more like listen to the whole episode. I was wondering more like a single tap for a random 1-min listen. 

> Does LOCUST still happen to you? how about on a newly subscribed channel?

🥲...yes it does. Even to newly subscribed youtube channels. (Audio mode only)

**Comment by XilinJia** [comment]
> I was wondering more like a single tap for a random 1-min listen.

can't you just stop it anytime you want?

For LOCUST and the lag, I can't imagine how it can happen yet.

**Comment by XilinJia** [comment]
Can you verify if LOCUST, MILLIPEDE, MOSQUITO and EARWIG still exist with version 6.11.3?

**Comment by Jackie7610** [comment]
Yes. Have just tested all three a moment ago. All of those bugs are in their place. 

I however got the chance to grab a stack trace of a bug that was caused by millipede. Remember the crash after scroll lag? That one


            ## Environment
Android version: 13
OS version: 4.14.186-27270957
Podcini version: 6.11.3
Model: SM-A325F
Device: a32
Product: a32xx
            
            ## Crash info
Time: 17-10-2024 11:36:00
Podcini version: 6.11.3

## StackTrace
```
java.lang.NullPointerException
	at ac.mdiq.podcini.ui.compose.EpisodesVMKt$EpisodeLazyColumn$7$invoke$lambda$29$lambda$28$$inlined$itemsIndexed$default$3.invoke(LazyDsl.kt:660)
	at ac.mdiq.podcini.ui.compose.EpisodesVMKt$EpisodeLazyColumn$7$invoke$lambda$29$lambda$28$$inlined$itemsIndexed$default$3.invoke(LazyDsl.kt:188)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:139)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.foundation.lazy.LazyListItemProviderImpl$Item$1.invoke(LazyListItemProvider.kt:79)
	at androidx.compose.foundation.lazy.LazyListItemProviderImpl$Item$1.invoke(LazyListItemProvider.kt:77)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
	at androidx.compose.foundation.lazy.layout.LazyLayoutPinnableItemKt.LazyLayoutPinnableItem(LazyLayoutPinnableItem.kt:58)
	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.Item(LazyListItemProvider.kt:77)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt$SkippableItem$1.invoke(LazyLayoutItemContentFactory.kt:136)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt$SkippableItem$1.invoke(LazyLayoutItemContentFactory.kt:135)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:85)
	at androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.SaveableStateProvider(LazySaveableStateHolder.kt:85)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:135)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.access$SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:1)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:102)
	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:92)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:176)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:493)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:97)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3595)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3522)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:743)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1122)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3876)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:516)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:488)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:479)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:463)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:895)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:125)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw(LazyListMeasuredItemProvider.kt:55)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:49)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-x0Ok8Vo(LazyListMeasure.kt:214)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(LazyList.kt:326)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:183)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke-0kLqBqw(LazyLayout.kt:119)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:112)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:725)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:135)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:188)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Padding.kt:414)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:188)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:316)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:315)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:140)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1782)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:40)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:696)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1222)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:367)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(MeasureAndLayoutDelegate.kt:463)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(AndroidComposeView.android.kt:1280)
	at androidx.compose.ui.node.LayoutNode.forceRemeasure(LayoutNode.kt:1296)
	at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:456)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:229)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:229)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:184)
	at androidx.compose.foundation.gestures.ScrollingLogic.performScroll-3eAAhYA(Scrollable.kt:717)
	at androidx.compose.foundation.gestures.ScrollingLogic.access$performScroll-3eAAhYA(Scrollable.kt:642)
	at androidx.compose.foundation.gestures.ScrollingLogic$performScrollForOverscroll$1.invoke-MK-Hz9U(Scrollable.kt:702)
	at androidx.compose.foundation.gestures.ScrollingLogic$performScrollForOverscroll$1.invoke(Scrollable.kt:700)
	at androidx.compose.foundation.AndroidEdgeEffectOverscrollEffect.applyToScroll-Rhakbz0(AndroidOverscroll.android.kt:494)
	at androidx.compose.foundation.gestures.ScrollingLogic$nestedScrollScope$1.scrollByWithOverscroll-OzD1aCk(Scrollable.kt:691)
	at androidx.compose.foundation.gestures.ScrollableNode$drag$2$1$1.invoke(Scrollable.kt:345)
	at androidx.compose.foundation.gestures.ScrollableNode$drag$2$1$1.invoke(Scrollable.kt:344)
	at androidx.compose.foundation.gestures.DragGestureNode$startListeningForEvents$1$1.invokeSuspend(Draggable.kt:437)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@b8c1823, androidx.compose.runtime.BroadcastFrameClock@8132120, StandaloneCoroutine{Cancelling}@2fd0ad9, AndroidUiDispatcher@be1ec9e]
```

**Comment by XilinJia** [comment]
Hum, that stacktrace doesn't tell too much, but I made a bit change, so we will see it happens again on the next version.

**Comment by XilinJia** [comment]
6.11.4 largely improved episodes list scroll. Let me know what happens with you.

**Comment by Jackie7610** [comment]
I tried 6.11.4 but alas! 🥲 It is the same. The LOCUST, MILLIPEDE, MOSQUITO are still there. I tried some previous versions to check where it started. LOCUST was from day 1 when the youtube feature was implemented. 
MOSQUITO was there ever since I found the app from F-droid. MILLIPEDE occured from the pre releases of JetPack Compose.

**Comment by XilinJia** [comment]
As it stands now, the issues of LOCUST, MILLIPEDE, MOSQUITO sound very peculiar.  I could never re-produce them.  Could narrow them down to certain conditions? Or could you try re-installing Podcini afresh and see if you still get them?

**Comment by XilinJia** [comment]
I noticed some serious lagging in some cases that I can't define. have to do with the phone: my S21 Android 14 phone has no issue while a high-end Android 9 phone has some trouble.  have to do with some podcasts: certain podcasts on my Android 9 phone behave very poorly while others don't have problem.

**Comment by XilinJia** [comment]
Hopefully MILLIPEDE is fixed in 6.11.6.  Try it.

**Comment by Jackie7610** [comment]
Hey dev. Just tried it with a fresh install from github. I think you're right about the phone part, I saw it happening only with samsung devices. It didn't happen with Vivo, Poco and Oppo as I've tried using my friend's device. 

This is the result and it's the same as before. I've tested all three.

https://upload.disroot.org/r/JoV5zMhk#A78DxVT6qJXUqrvdF7oOHxYapMt7jdUul1wKUmp/Rcs=

**Comment by XilinJia** [comment]
Thanks for the info.

Did you find 6.11.6 improved the scrolling for you compared with prior versions?

I tried your Nocturne Boulevard podcast, scrolling is very fast. Strangely, the icons are not the same as yours, mine's are somewhat reddish.

I tried your Nexpo podcast, opening the playerdetailed view has no problem

![Screenshot_20241019_075402_ac mdiq podcini R debug](https://github.com/user-attachments/assets/6c23d996-1521-42f6-ac21-3de41c5b0e8d)
![Screenshot_20241019_074332_ac mdiq podcini R debug](https://github.com/user-attachments/assets/dd0c7e6a-4d87-4f7d-b564-1334158c1736)

**Comment by XilinJia** [comment]
Regarding player detailed view not open, I wonder if you have WebView or Chrome browser installed on your phone? I can't say which one is definitely necessary, but that part uses webview to display the info.

**Comment by Jackie7610** [comment]
I use android system webview and that's on version 129 or something. Let me see the results after updating the webview

**Comment by Jackie7610** [comment]
Greetings Dev. It's been a while...
I'm writing to thank you for fixing LOCUST. I'm relieved...I can listen to YouTube media in audio form without any issues. Well...without the LOCUST issue.

Give me a moment while I update the bug reports as I have tracked down more

**Comment by XilinJia** [comment]
Thank you.  Look forward to more bug reports.

**Comment by XilinJia** [comment]
I see you added a couple items on the list. Editing a previous comment doesn't get me notified.  It's better to add a comment, or for better management, it's better to create a new bug report.

Could you review the list and update the status on every unresolved issue?

**Comment by XilinJia** [comment]
> Hello dev. Apologies for the late response as I was busy during my exams. I have updated the status also I will create a new issue for any new bugs found in the future if that'll make things easier

Best luck with the exams!
You don't really need create a separate issue for every bug, you can combine the related ones, but it's better to separate different issues.

**Comment by XilinJia** [comment]
> Also I can't seem to locate the option to sort out the navigation drawer items. Is it completely removed from the app itself in the latest update or is it hidden only from the settings page?

Yes, in 6.15.0, drawer customization is removed as there are fewer items on the drawer so customization appears not much needed.

**Comment by Jackie7610** [comment]
I see. Makes sense. Say dev, could you please look into the dynamic color settings as it is only applied as the background color (if set in dark and **not** full black) and does not affect the swtiches and other parts of the app. It always remains violet.

**Comment by Jackie7610** [comment]
Old bug; remembered today

- [ ] HORNET - The 'undo' feature in the history page after removing an item from history does not really 'undo' it.
